name: Deployment (DEV)

# Will deploy when the developer is pushing

concurrency:
  group: development
  cancel-in-progress: true


on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    concurrency: development
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy (DEV)
      run: echo "Deploying to DEV"
