name: Deployment (UAT)

# Will deploy when the developer is pushing

concurrency:
  group: UAT
  cancel-in-progress: false


on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy (UAT)
      run: echo "Deploying to UAT"
