name: Deployment (PROD)

# Will deploy on new tags only

concurrency:
  group: PROD
  cancel-in-progress: false


on:
  push:
    tags:
    - '*'
  release:
    types:
    - created



jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy (PROD)
      run: echo "Deploying to PROD"
