name: Deployment (PROD)

# Will deploy on new tags only

concurrency:
  group: production
  cancel-in-progress: false


on:
  push:
    tags:
    - '*'
  release:
    types:
    - created


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy (PROD)
      run: echo "Deploying to PROD"
